feat: convert to timestamp
perillaleaves/sns-frontend pull request #3
Opened 2023-01-21 08:37 UTC by 1yoouoo

layout 끝나고 첫 pr입니다

timestamp 방금 전, 몇분 전 ,, 구현입니다

2023-01-21 08:39 UTC, 1yoouoo commented on src/Views/PostItem/PostItem.tsx
> +  function timeForToday(value: string) {
postitem에서 함수 timeforToday 선언중인데 여기서 쓸지 부모컴포넌트로 뺄지 아에 다른 파일로 뺄지 봐주세요

2023-01-22 12:16 UTC, merged

2023-01-24 05:06 UTC, baleen37 requested changes

2023-01-24 05:06 UTC, baleen37 commented on src/Assets/SVG/HeartActivedSvg.tsx
> +      <span className="HeartActivedSvg" onClick={() => onClickHeart?.()}>
```suggestion
const HeartActivedSvg = ({ onClickHeart: ()=>{} = ()=>{} }: onClickHeartTypeProps) => {
  return (
    <StyledHeartActivedSvg>
      <span className="HeartActivedSvg" onClick={() => onClickHeart()}>
```

이렇게 함수 기본값 미리 넣어주는 방법도 있어요

2023-01-24 05:06 UTC, baleen37 commented on src/Views/InteractionBar/InteractionBar.tsx
> +    }
```suggestion
	setLikes(heartToggle ? 1 : -1);
```

2023-01-24 05:06 UTC, baleen37 commented on src/Views/PostItem/PostItem.tsx
> +            View all {data.commentsNumber} comments
CommentCount

2023-01-24 05:06 UTC, baleen37 commented on src/Views/PostList/PostList.tsx
> +        datas.map((data: dataType) => {
DataType 은 뭔가요?

다른 용어면 좋을 거 같아요

Data 보다 post? PostItem 어떤가요?

2023-01-24 05:06 UTC, baleen37 commented on src/utills/function/function.ts
> +  const betweenTime = Math.floor(
변수명을 분으로 표현하면 어떨까요?